import React, { useEffect, useState } from 'react';
import { Trash2, AlertOctagon, Terminal } from 'lucide-react';
import { Log } from '../types';

export const Logs: React.FC = () => {
  const [logs, setLogs] = useState<Log[]>([]);
  const [source, setSource] = useState('');
  const [level, setLevel] = useState('');
  const [limit, setLimit] = useState(100);
  const [isLoading, setIsLoading] = useState(true);

  const fetchLogs = async () => {
    setIsLoading(true);
    try {
      const url = `/api/logs?limit=${limit}&source=${source}&level=${level}`;
      const response = await fetch(url);
      if (!response.ok) {
        setLogs([]);
        return;
      }
      const data = await response.json();
      setLogs(Array.isArray(data) ? data : (data?.logs && Array.isArray(data.logs) ? data.logs : []));
    } catch (err) {
      console.error(err);
      setLogs([]);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
  }, [source, level, limit]);

  const handleClearLogs = async () => {
    if (!confirm('Are you sure you want to clear all system logs from database?')) return;
    
    try {
      await fetch('/api/logs/clear', { method: 'POST' });
      fetchLogs();
    } catch (err) {
      console.error(err);
    }
  };

  const sources = ['CSV_IMPORT', 'EMAIL_GENERATION', 'EMAIL_SENDING', 'OAUTH', 'API'];
  const levels = ['INFO', 'WARN', 'ERROR'];

  return (
    <div className="p-6 md:p-8 max-w-7xl mx-auto space-y-8 animate-in fade-in duration-200">
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-xl font-extrabold text-slate-900 tracking-tight">System Logs</h2>
          <p className="text-xs text-slate-500 mt-1">
            Audit trailing events generated by imports, campaign scheduler, and Gmail API services.
          </p>
        </div>

        <button
          onClick={handleClearLogs}
          className="flex items-center gap-2 px-4 py-2 bg-slate-100 hover:bg-rose-50 border border-slate-200 hover:border-rose-200 text-rose-700 rounded-xl text-xs transition-colors font-bold cursor-pointer"
        >
          <Trash2 className="w-4 h-4" />
          Clear Logs
        </button>
      </div>

      {/* Filters bar */}
      <div className="flex flex-wrap gap-4 items-center bg-white p-4 border border-slate-200/80 rounded-2xl shadow-xs">
        <div className="flex items-center gap-2 text-xs">
          <span className="text-slate-500 font-bold uppercase tracking-wider text-[10px]">Filter Source:</span>
          <select
            value={source}
            onChange={(e) => setSource(e.target.value)}
            className="rounded-xl border border-slate-300 bg-slate-50 px-3 py-1.5 text-xs text-slate-900 focus:outline-none focus:bg-white focus:border-slate-900"
          >
            <option value="">All Sources</option>
            {sources.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="text-slate-500 font-bold uppercase tracking-wider text-[10px]">Filter Level:</span>
          <select
            value={level}
            onChange={(e) => setLevel(e.target.value)}
            className="rounded-xl border border-slate-300 bg-slate-50 px-3 py-1.5 text-xs text-slate-900 focus:outline-none focus:bg-white focus:border-slate-900"
          >
            <option value="">All Levels</option>
            {levels.map((l) => (
              <option key={l} value={l}>{l}</option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="text-slate-500 font-bold uppercase tracking-wider text-[10px]">Show Limit:</span>
          <select
            value={limit}
            onChange={(e) => setLimit(Number(e.target.value))}
            className="rounded-xl border border-slate-300 bg-slate-50 px-3 py-1.5 text-xs text-slate-900 focus:outline-none focus:bg-white focus:border-slate-900"
          >
            <option value={20}>20 lines</option>
            <option value={50}>50 lines</option>
            <option value={100}>100 lines</option>
            <option value={250}>250 lines</option>
          </select>
        </div>
      </div>

      {/* Logs Sheet */}
      <div className="border border-slate-200 bg-white rounded-2xl overflow-hidden shadow-sm">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-slate-200 bg-slate-50 text-slate-600 uppercase font-bold text-[10px] tracking-wider font-sans">
                <th className="p-4">Timestamp</th>
                <th className="p-4">Level</th>
                <th className="p-4">Source</th>
                <th className="p-4">Message</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {isLoading ? (
                <tr>
                  <td colSpan={4} className="p-8 text-center">
                    <div className="animate-spin rounded-full h-5 w-5 border-2 border-slate-300 border-t-slate-800 mx-auto"></div>
                  </td>
                </tr>
              ) : logs.length === 0 ? (
                <tr>
                  <td colSpan={4} className="p-8 text-center text-slate-500 text-xs font-sans">
                    No system log entries match criteria.
                  </td>
                </tr>
              ) : (
                logs.map((log) => (
                  <tr key={log.id} className="hover:bg-slate-50/80 transition-colors">
                    <td className="p-4 text-slate-500 text-[11px] font-mono whitespace-nowrap">
                      {new Date(log.timestamp).toLocaleString()}
                    </td>
                    <td className="p-4">
                      <span className={`px-2 py-0.5 rounded text-[9px] font-bold uppercase tracking-wider border ${
                        log.level === 'ERROR'
                          ? 'bg-rose-50 border-rose-200 text-rose-800'
                          : log.level === 'WARN'
                          ? 'bg-amber-50 border-amber-200 text-amber-800'
                          : 'bg-slate-100 border-slate-200 text-slate-700'
                      }`}>
                        {log.level}
                      </span>
                    </td>
                    <td className="p-4 text-slate-900 font-bold tracking-wide text-[11px] font-sans">
                      {log.source}
                    </td>
                    <td className="p-4 text-slate-800 leading-relaxed max-w-xl truncate" title={log.message}>
                      {log.message}
                      {log.details && (
                        <div className="text-[10px] text-slate-600 mt-1 max-h-32 overflow-y-auto whitespace-pre-wrap select-all bg-slate-50 p-2.5 rounded-xl border border-slate-200 font-mono">
                          {log.details}
                        </div>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};
