import React, { useEffect, useState } from 'react';
import { Trash2, AlertOctagon, Terminal } from 'lucide-react';
import { Log } from '../types';

export const Logs: React.FC = () => {
  const [logs, setLogs] = useState<Log[]>([]);
  const [source, setSource] = useState('');
  const [level, setLevel] = useState('');
  const [limit, setLimit] = useState(100);
  const [isLoading, setIsLoading] = useState(true);

  const fetchLogs = async () => {
    setIsLoading(true);
    try {
      const url = `/api/logs?limit=${limit}&source=${source}&level=${level}`;
      const response = await fetch(url);
      const data = await response.json();
      setLogs(data);
    } catch (err) {
      console.error(err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchLogs();
  }, [source, level, limit]);

  const handleClearLogs = async () => {
    if (!confirm('Are you sure you want to clear all system logs from database?')) return;
    
    try {
      await fetch('/api/logs/clear', { method: 'POST' });
      fetchLogs();
    } catch (err) {
      console.error(err);
    }
  };

  const sources = ['CSV_IMPORT', 'EMAIL_GENERATION', 'EMAIL_SENDING', 'OAUTH', 'API'];
  const levels = ['INFO', 'WARN', 'ERROR'];

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6">
      
      {/* Header and filters */}
      <div className="flex flex-col sm:flex-row justify-between items-start sm:items-center gap-4">
        <div>
          <h2 className="text-xl font-bold text-neutral-100 tracking-tight">System Logs</h2>
          <p className="text-xs text-neutral-400 mt-1">
            Audit trailing events generated by imports, campaign scheduler, and Gmail API services.
          </p>
        </div>

        <button
          onClick={handleClearLogs}
          className="flex items-center gap-2 px-3 py-1.5 bg-neutral-900 border border-neutral-800 hover:bg-rose-950/20 hover:border-rose-900/35 text-rose-450 hover:text-rose-450 rounded-md text-xs transition-colors font-semibold"
        >
          <Trash2 className="w-4 h-4" />
          Clear Logs
        </button>
      </div>

      {/* Filters bar */}
      <div className="flex flex-wrap gap-4 items-center bg-zinc-900/10 p-4 border border-neutral-850 rounded-xl">
        <div className="flex items-center gap-2 text-xs">
          <span className="text-neutral-500 font-semibold uppercase tracking-wider text-[10px]">Filter Source:</span>
          <select
            value={source}
            onChange={(e) => setSource(e.target.value)}
            className="rounded-md border border-neutral-850 bg-zinc-950 px-3 py-1.5 text-xs text-neutral-300 focus:outline-none"
          >
            <option value="">All Sources</option>
            {sources.map((s) => (
              <option key={s} value={s}>{s}</option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="text-neutral-500 font-semibold uppercase tracking-wider text-[10px]">Filter Level:</span>
          <select
            value={level}
            onChange={(e) => setLevel(e.target.value)}
            className="rounded-md border border-neutral-850 bg-zinc-950 px-3 py-1.5 text-xs text-neutral-300 focus:outline-none"
          >
            <option value="">All Levels</option>
            {levels.map((l) => (
              <option key={l} value={l}>{l}</option>
            ))}
          </select>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <span className="text-neutral-500 font-semibold uppercase tracking-wider text-[10px]">Show Limit:</span>
          <select
            value={limit}
            onChange={(e) => setLimit(Number(e.target.value))}
            className="rounded-md border border-neutral-850 bg-zinc-950 px-3 py-1.5 text-xs text-neutral-300 focus:outline-none"
          >
            <option value={20}>20 lines</option>
            <option value={50}>50 lines</option>
            <option value={100}>100 lines</option>
            <option value={250}>250 lines</option>
          </select>
        </div>
      </div>

      {/* Logs Sheet */}
      <div className="border border-neutral-800 bg-zinc-950/20 rounded-xl overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-xs font-mono">
            <thead>
              <tr className="border-b border-neutral-900 bg-zinc-950/40 text-neutral-500 uppercase font-semibold text-[10px] tracking-wider font-sans">
                <th className="p-4">Timestamp</th>
                <th className="p-4">Level</th>
                <th className="p-4">Source</th>
                <th className="p-4">Message</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-neutral-900">
              {isLoading ? (
                <tr>
                  <td colSpan={4} className="p-8 text-center">
                    <div className="animate-spin rounded-full h-5 w-5 border-b-2 border-neutral-400 mx-auto"></div>
                  </td>
                </tr>
              ) : logs.length === 0 ? (
                <tr>
                  <td colSpan={4} className="p-8 text-center text-neutral-500 text-xs font-sans">
                    No system log entries match criteria.
                  </td>
                </tr>
              ) : (
                logs.map((log) => (
                  <tr key={log.id} className="hover:bg-neutral-900/20 transition-colors">
                    <td className="p-4 text-neutral-500 text-[10px] whitespace-nowrap">
                      {new Date(log.timestamp).toLocaleString()}
                    </td>
                    <td className="p-4">
                      <span className={`px-1.5 py-0.5 rounded text-[9px] font-bold border uppercase tracking-wider ${
                        log.level === 'ERROR'
                          ? 'bg-rose-950/20 border-rose-800/40 text-rose-450'
                          : log.level === 'WARN'
                          ? 'bg-amber-950/20 border-amber-800/40 text-amber-500'
                          : 'bg-zinc-900 border-neutral-800 text-neutral-400'
                      }`}>
                        {log.level}
                      </span>
                    </td>
                    <td className="p-4 text-neutral-400 font-semibold tracking-wide text-[10px]">
                      {log.source}
                    </td>
                    <td className="p-4 text-neutral-300 leading-relaxed max-w-xl truncate" title={log.message}>
                      {log.message}
                      {log.details && (
                        <div className="text-[10px] text-neutral-500 mt-1 max-h-32 overflow-y-auto whitespace-pre-wrap select-all bg-zinc-950/40 p-2 rounded border border-neutral-900/60 font-mono">
                          {log.details}
                        </div>
                      )}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>

    </div>
  );
};
